### PR TITLE
Toleration for security config pod

### PR DESCRIPTION
**Pull request by madhukarmmallia-plivo**
PR for fixing https://github.com/Opster/opensearch-k8s-operator/issues/292 to setup tolerations - adding security config pod.

Changes introduce a fields for enabling tolerations, affinity and node selector for the security config pod - useful for placing the pod appropriately.

### CODE REVIEW

**Comment by swoehrl-mw** [comment]
Hi @madhukarmmallia-plivo. Please make sure your PR follows all points from https://github.com/Opster/opensearch-k8s-operator/blob/main/docs/developing.md#submitting-a-pr.

**Comment by idanl21** [comment]
Closing that issue for now, 
if you wish you can still reOpen it

**Comment by kinseii** [comment]
Opening it up again. I also need nodeSelector and tolerations to be assigned to securityconfig jobs

**Comment by swoehrl-mw** [comment]
Hi @kinseii. The PR was closed due to inactivity by the autor. The referenced issue is still open and is waiting for someone else to implement it and provide a PR.

**Pull request closed without merging**
