### PR TITLE
Add imagePullSecret for operator

### LINKED ISSUE #618: imagePullSecret for operator
While we can specify imagePullSecret for the OS/OSD pods in the CR, currently we have no way to specify imagePullSecret for the operator pod itself.

### PR DESCRIPTION
**Pull request by saketmht**
Fixes #618 

Changes:

- Add `imagePullSecrets` field to the values.yaml
- Populate the SA for the operator with the imagePullSecrets
- Populate the deployment for the operator incase the SA is not created

### CODE REVIEW

**Review by swoehrl-mw — CHANGES_REQUESTED** [review]

**Comment by saketmht** [comment]
@swoehrl-mw Updated according to reviews

**Review by idanl21 — COMMENTED** [review]
Hey, it should be related to the controller deployment or the clusters deployment ?>

**Comment by saketmht** [comment]
> Hey, it should be related to the controller deployment or the clusters deployment ?>

We can already specify imagePullSecrets for the cluster pods through the OS CR. This is for the operator deployment itself.

**Review by idanl21 — APPROVED** [review]

**Review by swoehrl-mw — APPROVED** [review]

**Comment by mrpi** [comment]
Hey

we are looking forward to use this great project, but our cloud platform team says, we need an official release, that contains this fix. Is there a schedule for a version including this change? 

Thanks!

**Pull request merged**
