### PR TITLE
Upgrade operator to use go 1.19

### PR DESCRIPTION
**Pull request by swoehrl-mw**
* Configured project to use go 1.19
* Changed workflows to use go 1.19
* Upgraded ginkgo to v2
* Updated Makefile to newest standard as generated by kubebuilder

### CODE REVIEW

**Comment by swoehrl-mw** [comment]
@FactorT Since you already opened some PRs for updating part of the tooling could you please check if I got everything you had?

**Comment by FactorT** [comment]
@swoehrl-mw thank you, everything is here!

**Review by prudhvigodithi — APPROVED** [review]

**Comment by prudhvigodithi** [comment]
Thanks @swoehrl-mw and @FactorT

**Review by idanl21 — APPROVED** [review]

**Comment by prudhvigodithi** [comment]
Hey @swoehrl-mw, just noticed the following warnings, are those expected? :) 
```
make install
test -s /tmp/opensearch-k8s-operator/opensearch-operator/bin/controller-gen || GOBIN=/tmp/opensearch-k8s-operator/opensearch-operator/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.10.0
/tmp/opensearch-k8s-operator/opensearch-operator/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/tmp/opensearch-k8s-operator/opensearch-operator/bin/kustomize build config/crd | kubectl apply -f -
Warning: resource customresourcedefinitions/opensearchclusters.opensearch.opster.io is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
customresourcedefinition.apiextensions.k8s.io/opensearchclusters.opensearch.opster.io configured
Warning: resource customresourcedefinitions/opensearchroles.opensearch.opster.io is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
customresourcedefinition.apiextensions.k8s.io/opensearchroles.opensearch.opster.io configured
Warning: resource customresourcedefinitions/opensearchuserrolebindings.opensearch.opster.io is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
customresourcedefinition.apiextensions.k8s.io/opensearchuserrolebindings.opensearch.opster.io configured
Warning: resource customresourcedefinitions/opensearchusers.opensearch.opster.io is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
customresourcedefinition.apiextensions.k8s.io/opensearchusers.opensearch.opster.io configured
```
@idanl21

**Comment by swoehrl-mw** [comment]
@prudhvigodithi 
Those warnings are no problem. My guess is you installed the CRDs via helm initially. That way they do not have the annotation, but this is only cosmetic.

**Pull request merged**
