### PR TITLE
Enhanced Monitoring design document

### PR DESCRIPTION
**Pull request by asafm**
Added diagram in Mermaid.js format
Added overview
Rephrased a bit

### CODE REVIEW

**Comment by asafm** [comment]
@a-pel-a Can you take a look?

**Comment by a-pel-a** [comment]
Looks good, thanks!
It would be nice to make changes to the content in terms of modified and added sections

**Comment by asafm** [comment]
> It would be nice to make changes to the content in terms of modified and added sections
@a-pel-a Can you please be more specific? Is that something you want me to add in this PR?

**Comment by asafm** [comment]
Who can approve the workflows execution?

**Review by idanl21 — APPROVED** [review]

**Pull request merged**
