### PR TITLE
added option to use emptyDir as additional mount

### PR DESCRIPTION
**Pull request by mdarii**
related to issue: https://github.com/Opster/opensearch-k8s-operator/issues/484

This commit would allow to add additional volumes as emptyDir, this is necessary if `readOnlyRootFilesystem=true`

### CODE REVIEW

**Comment by idanl21** [comment]
@mdarii 
Please take a look

**Review by swoehrl-mw — CHANGES_REQUESTED** [review]
Hi @mdarii.
Thank you for your contribution.

I have some comments:
* Please add a unittest for the new functionality to verify it works (you can extend the test in `controllers/cluster_test.go` by adding an additionalVolume to the spec and verifying the volume(mount) is part of the created STS).
* Extend the section on "Additional Volumes" in the userguide
* Extend the CRD reference (`docs/designs/crd.md`)

**Comment by mdarii** [comment]
Hi @swoehrl-mw , I've updated my PR.

**Comment by swoehrl-mw** [comment]
@mdarii Code looks good, please check why the tests fail and fix if necessary.

**Comment by mdarii** [comment]
@swoehrl-mw  I'll look into it, but most probably next week

**Comment by mdarii** [comment]
@swoehrl-mw  looks like I've found typo, can you please retrigger pipeline?

**Comment by swoehrl-mw** [comment]
@mdarii Could you please merge in the current main? There is a fix that should deal with the failing functionaltests check so we can then hopefully merge this PR.

**Comment by idanl21** [comment]
@mdarii 
Hey , do you plan to continue that PR ?

**Comment by mdarii** [comment]
> @mdarii Hey , do you plan to continue that PR ?

yes, I'll try to come back to it somehow this week

**Comment by mdarii** [comment]
@swoehrl-mw  could you trigger pipeline please, I've synced repo with master

**Review by swoehrl-mw — APPROVED** [review]
LGTM

**Pull request merged**
